[threat_hunt_response_plans]
external_type = kvstore
collection = threat_hunt_response_plans
fields_list = _key, plan_id, mitre_technique_id, technique_name, security_domain, containment_steps, investigation_steps, eradication_steps, recovery_steps, escalation_criteria

[threat_hunt_notable_staging]
external_type = kvstore
collection = threat_hunt_notable_staging
fields_list = _key, _time, rule_name, rule_description, security_domain, severity, drilldown_search, drilldown_name, src, dest, user, mitre_attack_id, status, processed_time
